### ISSUE TITLE
7.0的手机必现闪退

### ISSUE THREAD

**Issue by yanchunlan** [qiyu-kefu/Qiyu_Android_SDK#1]
java.lang.NullPointerException: Attempt to read from field 'long com.qiyukf.unicorn.api.ConsultSource.staffId' on a null object reference
                                                            at com.qiyukf.unicorn.g.c.a(Unknown Source)
                                                            at com.qiyukf.unicorn.ui.fragment.ServiceMessageFragment$13.a(Unknown Source)
                                                            at com.qiyukf.unicorn.ui.a.a$3.onClick(Unknown Source)
                                                            at android.view.View.performClick(View.java:5646)
                                                            at android.view.View$PerformClick.run(View.java:22459)
                                                            at android.os.Handler.handleCallback(Handler.java:761)
                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                            at android.os.Looper.loop(Looper.java:156)
                                                            at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by yanchunlan** [comment]
进入客服界面，点击人工客服，退出，再进入界面点击人工客服，闪退
